//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TimeZ
{
    using System;
    using System.Collections.Generic;
    
    public partial class TimesheetExcel
    {
        public int ID { get; set; }
        public Nullable<System.DateTime> Week_Commence { get; set; }
        public string Team { get; set; }
        public string Shift { get; set; }
        public string Name { get; set; }
        public string Application { get; set; }
        public string Task { get; set; }
        public string Reference_Number { get; set; }
        public string Activity { get; set; }
        public string Release { get; set; }
        public string Priority_Severity { get; set; }
        public string Description { get; set; }
        public Nullable<System.DateTime> Start_Date { get; set; }
        public Nullable<double> Hours_spent_this_week { get; set; }
        public string Month { get; set; }
        public Nullable<int> Year { get; set; }
    }
}
