//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TimeSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Entry
    {
        public string WeekStart { get; set; }
        public string Team { get; set; }
        public string Shift { get; set; }
        public string Name { get; set; }
        public string Application { get; set; }
        public string TaskType { get; set; }
        public string Activity { get; set; }
        public string Release { get; set; }
        public string Description { get; set; }
        public string StartDate { get; set; }
        public double HoursSpent { get; set; }
        public short Id { get; set; }
        public string Reference { get; set; }
    }
}
